// auto-generated by napi-zig. do not edit.

export const version: string;
export const maxBuffer: number;
export function add(a0: number, a1: number): number;
export function double(a0: number): number;
export function greet(a0: string): string;
export function parse(a0: string): string;
export function compile(a0: { filePath: string; lineCount: number; verbose?: boolean }): string;
export function log(a0: "debug" | "info" | "warning" | "errorLevel", a1: string): string;
export namespace crypto {
  function hash(a0: string): string;
  function verify(a0: string, a1: string): boolean;
}

export class Counter {
  constructor(a0: number);
  increment(): number;
  addN(a0: number): number;
  get(): number;
  reset(): void;
}

export function asyncFib(a0: number): unknown;
export function sum(...args: unknown[]): unknown;
export function forEach(a0: unknown[], a1: (...args: unknown[]) => unknown): void;
