// Comptime TypeScript declaration generator.
//
// Walks a `Module` the same way `module.zig` does and emits a `.d.ts`
// describing every JS-visible export. Used by the build system: a tiny
// helper executable imports the user's module, calls `generate`, and
// writes the result to disk. `napi.module()` is a no-op in that exe
// (skipped because output_mode != .Lib) so there's no symbol clash.

const std = @import("std");
const util = @import("util.zig");
const val_mod = @import("val.zig");
const env_mod = @import("env.zig");
const class_mod = @import("class.zig");

const Val = val_mod.Val;
const Callback = val_mod.Callback;
const Env = env_mod.Env;

/// Generate a `.d.ts` for every public declaration of `Module`.
/// All work happens at comptime; the result is a static string.
pub fn generate(comptime Module: type) []const u8 {
    comptime {
        var out: []const u8 = "// Auto-generated by napi-zig. Do not edit.\n\n";
        out = out ++ emitNamespace(Module, 0, .top);
        return out;
    }
}

const Where = enum { top, nested };

fn emitNamespace(comptime T: type, comptime indent: usize, comptime where: Where) []const u8 {
    comptime {
        var out: []const u8 = "";
        const decls = @typeInfo(T).@"struct".decls;

        for (decls) |decl| {
            if (decl.name[0] == '_') continue;
            const name = decl.name;
            const value = @field(T, name);
            const VT = @TypeOf(value);
            const js_name = util.snakeToCamelSlice(name);
            const pad = spaces(indent);

            if (VT == type) {
                if (@typeInfo(value) == .@"struct") {
                    if (class_mod.isClass(value)) {
                        out = out ++ emitClass(js_name, value, indent, where);
                        continue;
                    }
                    if (hasExportable(value)) {
                        const prefix = if (where == .top) "export namespace " else pad ++ "namespace ";
                        out = out ++ prefix ++ js_name ++ " {\n";
                        out = out ++ emitNamespace(value, indent + 2, .nested);
                        out = out ++ pad ++ "}\n\n";
                    }
                }
                continue;
            }

            switch (@typeInfo(VT)) {
                .@"fn" => {
                    out = out ++ emitFn(name, js_name, VT, value, indent, where);
                },
                .comptime_int, .comptime_float, .int, .float, .bool, .@"enum", .@"struct", .optional, .pointer => {
                    if (isExportableConst(VT)) {
                        const kw = if (where == .top) "export const " else pad ++ "const ";
                        out = out ++ kw ++ js_name ++ ": " ++ tsType(VT) ++ ";\n";
                    }
                },
                else => {},
            }
        }
        return out;
    }
}

fn emitClass(comptime js_name: []const u8, comptime Wrapper: type, comptime indent: usize, comptime where: Where) []const u8 {
    comptime {
        const T = Wrapper.__napi_class_inner;
        const pad = spaces(indent);
        const inner_pad = spaces(indent + 2);
        const prefix = if (where == .top) "export class " else pad ++ "class ";

        var out: []const u8 = prefix ++ js_name ++ " {\n";

        // constructor signature
        const init_fn = @field(T, "init");
        const InitFn = @TypeOf(init_fn);
        const init_info = @typeInfo(InitFn).@"fn";
        const init_params = init_info.params;
        const inject_env_init = init_params.len > 0 and init_params[0].type != null and init_params[0].type.? == Env;
        const init_start: usize = if (inject_env_init) 1 else 0;

        var ctor_args: []const u8 = "";
        var first = true;
        for (init_start..init_params.len) |i| {
            const ParamT = init_params[i].type.?;
            const arg_name = std.fmt.comptimePrint("a{d}", .{i - init_start});
            if (!first) ctor_args = ctor_args ++ ", ";
            first = false;
            const opt = @typeInfo(ParamT) == .optional or
                (@typeInfo(ParamT) == .@"struct" and isAllDefaults(ParamT));
            ctor_args = ctor_args ++ arg_name ++ (if (opt) "?: " else ": ") ++ tsType(ParamT);
        }
        out = out ++ inner_pad ++ "constructor(" ++ ctor_args ++ ");\n";

        // methods
        const methods = class_mod.collectMethods(T);
        for (methods) |m| {
            const m_fn = @field(T, m);
            const MFn = @TypeOf(m_fn);
            const m_info = @typeInfo(MFn).@"fn";
            const params = m_info.params;
            const inject_env = params.len > 1 and params[1].type != null and params[1].type.? == Env;
            const m_start: usize = if (inject_env) 2 else 1;
            const Return = m_info.return_type orelse void;
            const Payload = switch (@typeInfo(Return)) {
                .error_union => |eu| eu.payload,
                else => Return,
            };

            var args: []const u8 = "";
            var f2 = true;
            for (m_start..params.len) |i| {
                const ParamT = params[i].type.?;
                const arg_name = std.fmt.comptimePrint("a{d}", .{i - m_start});
                if (!f2) args = args ++ ", ";
                f2 = false;
                const opt = @typeInfo(ParamT) == .optional or
                    (@typeInfo(ParamT) == .@"struct" and isAllDefaults(ParamT));
                args = args ++ arg_name ++ (if (opt) "?: " else ": ") ++ tsType(ParamT);
            }

            const ret_ts = if (Payload == val_mod.Val) "unknown" else tsType(Payload);
            out = out ++ inner_pad ++ util.snakeToCamelSlice(m) ++ "(" ++ args ++ "): " ++ ret_ts ++ ";\n";
        }

        out = out ++ pad ++ "}\n\n";
        return out;
    }
}

fn emitFn(comptime name: []const u8, comptime js_name: []const u8, comptime Fn: type, comptime func: anytype, comptime indent: usize, comptime where: Where) []const u8 {
    _ = name;
    _ = func;
    comptime {
        const info = @typeInfo(Fn).@"fn";
        const params = info.params;
        const Return = info.return_type orelse void;
        const Payload = switch (@typeInfo(Return)) {
            .error_union => |eu| eu.payload,
            else => Return,
        };

        // Detect raw mode: `(Env, CallInfo) !Val` — no inferable signature.
        const is_raw = params.len >= 2 and
            params[0].type != null and params[0].type.? == Env and
            params[1].type != null and params[1].type.? == val_mod.CallInfo;

        const pad = spaces(indent);
        const kw = if (where == .top) "export function " else pad ++ "function ";

        if (is_raw) {
            // Raw functions take unknown args, return unknown.
            return kw ++ js_name ++ "(...args: unknown[]): unknown;\n";
        }

        const inject_env = params.len > 0 and params[0].type != null and params[0].type.? == Env;
        const start: usize = if (inject_env) 1 else 0;

        var args: []const u8 = "";
        var first = true;
        for (start..params.len) |i| {
            const T = params[i].type.?;
            const arg_name = std.fmt.comptimePrint("a{d}", .{i - start});
            if (!first) args = args ++ ", ";
            first = false;
            const optional = @typeInfo(T) == .optional or
                (@typeInfo(T) == .@"struct" and isAllDefaults(T));
            args = args ++ arg_name ++ (if (optional) "?: " else ": ") ++ tsType(T);
        }

        const ret_ts = if (Payload == val_mod.Val) "unknown" else tsType(Payload);
        const is_async = looksAsync(Payload);
        const ret = if (is_async) ret_ts else ret_ts;

        return kw ++ js_name ++ "(" ++ args ++ "): " ++ ret ++ ";\n";
    }
}

// ── Type translation ──────────────────────────────────────────────────

fn tsType(comptime T: type) []const u8 {
    comptime {
        if (T == val_mod.Val) return "unknown";
        if (T == val_mod.Callback) return "(...args: unknown[]) => unknown";

        return switch (@typeInfo(T)) {
            .void => "void",
            .bool => "boolean",
            .comptime_int, .comptime_float => "number",
            .int => |info| switch (info.bits) {
                0...32 => "number",
                33...53 => "number",
                54...64 => "bigint",
                else => "number",
            },
            .float => "number",
            .optional => |opt| tsType(opt.child) ++ " | null",
            .@"enum" => |info| blk: {
                var s: []const u8 = "";
                for (info.fields, 0..) |f, i| {
                    if (i > 0) s = s ++ " | ";
                    s = s ++ "\"" ++ util.snakeToCamelSlice(f.name) ++ "\"";
                }
                break :blk s;
            },
            .pointer => |info| {
                if (info.size == .slice and info.child == u8) return "string";
                if (info.size == .slice) return tsType(info.child) ++ "[]";
                if (info.size == .one) {
                    const child = @typeInfo(info.child);
                    if (child == .array and child.array.child == u8) return "string";
                }
                return "unknown";
            },
            .array => |info| if (info.child == u8) "string" else tsType(info.child) ++ "[]",
            .@"struct" => |info| blk: {
                if (info.is_tuple) {
                    var s: []const u8 = "[";
                    for (info.fields, 0..) |f, i| {
                        if (i > 0) s = s ++ ", ";
                        s = s ++ tsType(f.type);
                    }
                    break :blk s ++ "]";
                }
                if (@hasDecl(T, "_dts")) break :blk T._dts;
                var s: []const u8 = "{ ";
                for (info.fields, 0..) |f, i| {
                    if (i > 0) s = s ++ "; ";
                    const opt_marker = if (f.default_value_ptr != null or @typeInfo(f.type) == .optional) "?" else "";
                    s = s ++ util.snakeToCamelSlice(f.name) ++ opt_marker ++ ": " ++ tsType(f.type);
                }
                break :blk s ++ " }";
            },
            else => "unknown",
        };
    }
}

// ── Helpers ───────────────────────────────────────────────────────────

fn isExportableConst(comptime T: type) bool {
    return switch (@typeInfo(T)) {
        .comptime_int, .comptime_float, .int, .float, .bool, .@"enum", .optional => true,
        .@"struct" => T != val_mod.Val,
        .pointer => |ptr| blk: {
            if (ptr.size == .slice and ptr.child == u8) break :blk true;
            if (ptr.size == .one) {
                const child = @typeInfo(ptr.child);
                if (child == .array and child.array.child == u8) break :blk true;
            }
            break :blk false;
        },
        else => false,
    };
}

fn hasExportable(comptime T: type) bool {
    if (@typeInfo(T) != .@"struct") return false;
    const decls = @typeInfo(T).@"struct".decls;
    for (decls) |d| {
        if (d.name[0] == '_') continue;
        const VT = @TypeOf(@field(T, d.name));
        if (VT == type) {
            const Inner = @field(T, d.name);
            if (@typeInfo(Inner) == .@"struct") {
                if (class_mod.isClass(Inner)) return true;
                if (hasExportable(Inner)) return true;
            }
            continue;
        }
        switch (@typeInfo(VT)) {
            .@"fn" => return true,
            .comptime_int, .comptime_float, .int, .float, .bool, .@"enum", .optional => return true,
            .@"struct" => if (VT != val_mod.Val) return true,
            .pointer => |ptr| {
                if (ptr.size == .slice and ptr.child == u8) return true;
                if (ptr.size == .one) {
                    const child = @typeInfo(ptr.child);
                    if (child == .array and child.array.child == u8) return true;
                }
            },
            else => {},
        }
    }
    return false;
}

fn isAllDefaults(comptime T: type) bool {
    const info = @typeInfo(T);
    if (info != .@"struct") return false;
    for (info.@"struct".fields) |f| {
        if (f.default_value_ptr == null) return false;
    }
    return true;
}

fn spaces(comptime n: usize) []const u8 {
    comptime {
        var s: []const u8 = "";
        var i: usize = 0;
        while (i < n) : (i += 1) s = s ++ " ";
        return s;
    }
}

fn looksAsync(comptime T: type) bool {
    return T == val_mod.Val;
}

// ── Tests ─────────────────────────────────────────────────────────────

const testing = std.testing;

test "generate emits export function for plain fn" {
    const M = struct {
        pub fn add(_: i32, _: i32) i32 {
            return 0;
        }
    };
    const dts = comptime generate(M);
    try testing.expect(std.mem.indexOf(u8, dts, "export function add(a0: number, a1: number): number;") != null);
}

test "generate camelCases snake_case names" {
    const M = struct {
        pub fn read_file(_: []const u8) []const u8 {
            return "";
        }
    };
    const dts = comptime generate(M);
    try testing.expect(std.mem.indexOf(u8, dts, "readFile(") != null);
}

test "generate emits namespace for nested struct" {
    const M = struct {
        pub const crypto = struct {
            pub fn hash(_: []const u8) [32]u8 {
                return undefined;
            }
        };
    };
    const dts = comptime generate(M);
    try testing.expect(std.mem.indexOf(u8, dts, "export namespace crypto") != null);
    try testing.expect(std.mem.indexOf(u8, dts, "function hash(") != null);
}

test "generate emits exports for constants" {
    const M = struct {
        pub const version: []const u8 = "1.0.0";
        pub const max_buf: u32 = 4096;
    };
    const dts = comptime generate(M);
    try testing.expect(std.mem.indexOf(u8, dts, "export const version: string;") != null);
    try testing.expect(std.mem.indexOf(u8, dts, "export const maxBuf: number;") != null);
}

test "generate emits export class for napi.class wrapper" {
    const M = struct {
        pub const Counter = class_mod.class("Counter", struct {
            value: i32,
            pub fn init(start: i32) @This() {
                return .{ .value = start };
            }
            pub fn increment(self: *@This()) i32 {
                self.value += 1;
                return self.value;
            }
            pub fn get(self: *const @This()) i32 {
                return self.value;
            }
        });
    };
    const dts = comptime generate(M);
    try testing.expect(std.mem.indexOf(u8, dts, "export class Counter {") != null);
    try testing.expect(std.mem.indexOf(u8, dts, "constructor(a0: number);") != null);
    try testing.expect(std.mem.indexOf(u8, dts, "increment(): number;") != null);
    try testing.expect(std.mem.indexOf(u8, dts, "get(): number;") != null);
}

test "tsType maps enums to string union" {
    const E = enum { ok, not_found, internal_error };
    const ts = comptime tsType(E);
    try testing.expect(std.mem.indexOf(u8, ts, "\"ok\"") != null);
    try testing.expect(std.mem.indexOf(u8, ts, "\"notFound\"") != null);
    try testing.expect(std.mem.indexOf(u8, ts, "\"internalError\"") != null);
}
