// Comptime TypeScript declaration generator.
//
// Walks a `Module` the same way `module.zig` does and emits a `.d.ts`
// describing every JS-visible export. Used by the build system: a tiny
// helper executable imports the user's module, calls `generate`, and
// writes the result to disk. `napi.module()` is a no-op in that exe
// (skipped because output_mode != .Lib) so there's no symbol clash.

const std = @import("std");
const util = @import("util.zig");
const val_mod = @import("val.zig");
const env_mod = @import("env.zig");
const class_mod = @import("class.zig");

const Val = val_mod.Val;
const Env = env_mod.Env;

/// Generate a `.d.ts` for every public declaration of `Module`.
/// All work happens at comptime; the result is a static string.
pub fn generate(comptime Module: type) []const u8 {
    comptime {
        var out: []const u8 = "// Auto-generated by napi-zig. Do not edit.\n\n";
        out = out ++ emitNamespace(Module, 0, .top);
        return out;
    }
}

const Where = enum { top, nested };

fn emitNamespace(comptime T: type, comptime indent: usize, comptime where: Where) []const u8 {
    comptime {
        var out: []const u8 = "";
        const decls = @typeInfo(T).@"struct".decls;

        for (decls) |decl| {
            if (decl.name[0] == '_') continue;
            const name = decl.name;
            const value = @field(T, name);
            const VT = @TypeOf(value);
            const js_name = util.snakeToCamelSlice(name);
            const pad = spaces(indent);

            if (VT == type) {
                if (@typeInfo(value) == .@"struct") {
                    if (class_mod.isClass(value)) {
                        out = out ++ emitClass(js_name, value, indent, where);
                        continue;
                    }
                    if (hasExportable(value)) {
                        const prefix = if (where == .top) "export namespace " else pad ++ "namespace ";
                        out = out ++ prefix ++ js_name ++ " {\n";
                        out = out ++ emitNamespace(value, indent + 2, .nested);
                        out = out ++ pad ++ "}\n\n";
                    }
                }
                continue;
            }

            switch (@typeInfo(VT)) {
                .@"fn" => {
                    out = out ++ emitFn(js_name, VT, indent, where);
                },
                .comptime_int, .comptime_float, .int, .float, .bool, .@"enum", .@"struct", .optional, .pointer => {
                    if (isExportableConst(VT)) {
                        const kw = if (where == .top) "export const " else pad ++ "const ";
                        out = out ++ kw ++ js_name ++ ": " ++ tsType(VT) ++ ";\n";
                    }
                },
                else => {},
            }
        }
        return out;
    }
}

fn emitFn(comptime js_name: []const u8, comptime Fn: type, comptime indent: usize, comptime where: Where) []const u8 {
    comptime {
        const info = @typeInfo(Fn).@"fn";
        const params = info.params;
        const kw = if (where == .top) "export function " else spaces(indent) ++ "function ";

        // Raw mode `(Env, CallInfo) !Val`, no inferable signature.
        if (params.len >= 2 and
            params[0].type.? == Env and
            params[1].type.? == val_mod.CallInfo)
        {
            return kw ++ js_name ++ "(...args: unknown[]): unknown;\n";
        }

        const start: usize = if (params.len > 0 and params[0].type.? == Env) 1 else 0;
        return kw ++ js_name ++ "(" ++ paramList(params, start) ++ "): " ++ returnTs(info) ++ ";\n";
    }
}

fn emitClass(comptime js_name: []const u8, comptime Wrapper: type, comptime indent: usize, comptime where: Where) []const u8 {
    comptime {
        const T = Wrapper.__napi_class_inner;
        const pad = spaces(indent);
        const inner = spaces(indent + 2);
        const prefix = if (where == .top) "export class " else pad ++ "class ";

        var out: []const u8 = prefix ++ js_name ++ " {\n";

        // constructor: skip Env if injected as the first param of init.
        const init_info = @typeInfo(@TypeOf(@field(T, "init"))).@"fn";
        const init_skip: usize = if (init_info.params.len > 0 and init_info.params[0].type.? == Env) 1 else 0;
        out = out ++ inner ++ "constructor(" ++ paramList(init_info.params, init_skip) ++ ");\n";

        // methods: skip self (always) plus optional Env injection.
        for (class_mod.collectMethods(T)) |m| {
            const m_info = @typeInfo(@TypeOf(@field(T, m))).@"fn";
            const m_skip: usize = if (m_info.params.len > 1 and m_info.params[1].type.? == Env) 2 else 1;
            out = out ++ inner ++ util.snakeToCamelSlice(m) ++ "(" ++
                paramList(m_info.params, m_skip) ++ "): " ++ returnTs(m_info) ++ ";\n";
        }

        return out ++ pad ++ "}\n\n";
    }
}

// Build a TypeScript parameter list for a Zig fn param array, skipping
// the first `start` entries (used to drop self / Env injections). Each
// param is named `a0`, `a1`, ..., generic but unambiguous.
fn paramList(comptime params: []const std.builtin.Type.Fn.Param, comptime start: usize) []const u8 {
    comptime {
        var out: []const u8 = "";
        for (start..params.len) |i| {
            const T = params[i].type.?;
            if (i > start) out = out ++ ", ";
            const opt = @typeInfo(T) == .optional or
                (@typeInfo(T) == .@"struct" and isAllDefaults(T));
            out = out ++ std.fmt.comptimePrint("a{d}", .{i - start}) ++ (if (opt) "?: " else ": ") ++ tsType(T);
        }
        return out;
    }
}

fn returnTs(comptime info: std.builtin.Type.Fn) []const u8 {
    comptime {
        const Return = info.return_type orelse void;
        const Payload = switch (@typeInfo(Return)) {
            .error_union => |eu| eu.payload,
            else => Return,
        };
        return if (Payload == val_mod.Val) "unknown" else tsType(Payload);
    }
}

// ── Type translation ──────────────────────────────────────────────────

fn tsType(comptime T: type) []const u8 {
    comptime {
        if (T == val_mod.Val) return "unknown";
        if (T == val_mod.Callback) return "(...args: unknown[]) => unknown";

        return switch (@typeInfo(T)) {
            .void => "void",
            .bool => "boolean",
            .comptime_int, .comptime_float => "number",
            .int => |info| switch (info.bits) {
                0...32 => "number",
                33...53 => "number",
                54...64 => "bigint",
                else => "number",
            },
            .float => "number",
            .optional => |opt| tsType(opt.child) ++ " | null",
            .@"enum" => |info| blk: {
                var s: []const u8 = "";
                for (info.fields, 0..) |f, i| {
                    if (i > 0) s = s ++ " | ";
                    s = s ++ "\"" ++ util.snakeToCamelSlice(f.name) ++ "\"";
                }
                break :blk s;
            },
            .pointer => |info| {
                if (info.size == .slice and info.child == u8) return "string";
                if (info.size == .slice) return tsType(info.child) ++ "[]";
                if (info.size == .one) {
                    const child = @typeInfo(info.child);
                    if (child == .array and child.array.child == u8) return "string";
                }
                return "unknown";
            },
            .array => |info| if (info.child == u8) "string" else tsType(info.child) ++ "[]",
            .@"struct" => |info| blk: {
                if (info.is_tuple) {
                    var s: []const u8 = "[";
                    for (info.fields, 0..) |f, i| {
                        if (i > 0) s = s ++ ", ";
                        s = s ++ tsType(f.type);
                    }
                    break :blk s ++ "]";
                }
                if (@hasDecl(T, "_dts")) break :blk T._dts;
                var s: []const u8 = "{ ";
                for (info.fields, 0..) |f, i| {
                    if (i > 0) s = s ++ "; ";
                    const opt_marker = if (f.default_value_ptr != null or @typeInfo(f.type) == .optional) "?" else "";
                    s = s ++ util.snakeToCamelSlice(f.name) ++ opt_marker ++ ": " ++ tsType(f.type);
                }
                break :blk s ++ " }";
            },
            else => "unknown",
        };
    }
}

// ── Helpers ───────────────────────────────────────────────────────────

fn isExportableConst(comptime T: type) bool {
    return switch (@typeInfo(T)) {
        .comptime_int, .comptime_float, .int, .float, .bool, .@"enum", .optional => true,
        .@"struct" => T != val_mod.Val,
        .pointer => |ptr| blk: {
            if (ptr.size == .slice and ptr.child == u8) break :blk true;
            if (ptr.size == .one) {
                const child = @typeInfo(ptr.child);
                if (child == .array and child.array.child == u8) break :blk true;
            }
            break :blk false;
        },
        else => false,
    };
}

fn hasExportable(comptime T: type) bool {
    if (@typeInfo(T) != .@"struct") return false;
    const decls = @typeInfo(T).@"struct".decls;
    for (decls) |d| {
        if (d.name[0] == '_') continue;
        const VT = @TypeOf(@field(T, d.name));
        if (VT == type) {
            const Inner = @field(T, d.name);
            if (@typeInfo(Inner) == .@"struct") {
                if (class_mod.isClass(Inner)) return true;
                if (hasExportable(Inner)) return true;
            }
            continue;
        }
        switch (@typeInfo(VT)) {
            .@"fn" => return true,
            .comptime_int, .comptime_float, .int, .float, .bool, .@"enum", .optional => return true,
            .@"struct" => if (VT != val_mod.Val) return true,
            .pointer => |ptr| {
                if (ptr.size == .slice and ptr.child == u8) return true;
                if (ptr.size == .one) {
                    const child = @typeInfo(ptr.child);
                    if (child == .array and child.array.child == u8) return true;
                }
            },
            else => {},
        }
    }
    return false;
}

fn isAllDefaults(comptime T: type) bool {
    const info = @typeInfo(T);
    if (info != .@"struct") return false;
    for (info.@"struct".fields) |f| {
        if (f.default_value_ptr == null) return false;
    }
    return true;
}

fn spaces(comptime n: usize) []const u8 {
    comptime {
        var s: []const u8 = "";
        var i: usize = 0;
        while (i < n) : (i += 1) s = s ++ " ";
        return s;
    }
}

// ── Tests ─────────────────────────────────────────────────────────────

const testing = std.testing;

test "generate emits export function for plain fn" {
    const M = struct {
        pub fn add(_: i32, _: i32) i32 {
            return 0;
        }
    };
    const dts = comptime generate(M);
    try testing.expect(std.mem.indexOf(u8, dts, "export function add(a0: number, a1: number): number;") != null);
}

test "generate camelCases snake_case names" {
    const M = struct {
        pub fn read_file(_: []const u8) []const u8 {
            return "";
        }
    };
    const dts = comptime generate(M);
    try testing.expect(std.mem.indexOf(u8, dts, "readFile(") != null);
}

test "generate emits namespace for nested struct" {
    const M = struct {
        pub const crypto = struct {
            pub fn hash(_: []const u8) [32]u8 {
                return undefined;
            }
        };
    };
    const dts = comptime generate(M);
    try testing.expect(std.mem.indexOf(u8, dts, "export namespace crypto") != null);
    try testing.expect(std.mem.indexOf(u8, dts, "function hash(") != null);
}

test "generate emits exports for constants" {
    const M = struct {
        pub const version: []const u8 = "1.0.0";
        pub const max_buf: u32 = 4096;
    };
    const dts = comptime generate(M);
    try testing.expect(std.mem.indexOf(u8, dts, "export const version: string;") != null);
    try testing.expect(std.mem.indexOf(u8, dts, "export const maxBuf: number;") != null);
}

test "generate emits export class for napi.class wrapper" {
    const M = struct {
        pub const Counter = class_mod.class("Counter", struct {
            value: i32,
            pub fn init(start: i32) @This() {
                return .{ .value = start };
            }
            pub fn increment(self: *@This()) i32 {
                self.value += 1;
                return self.value;
            }
            pub fn get(self: *const @This()) i32 {
                return self.value;
            }
        });
    };
    const dts = comptime generate(M);
    try testing.expect(std.mem.indexOf(u8, dts, "export class Counter {") != null);
    try testing.expect(std.mem.indexOf(u8, dts, "constructor(a0: number);") != null);
    try testing.expect(std.mem.indexOf(u8, dts, "increment(): number;") != null);
    try testing.expect(std.mem.indexOf(u8, dts, "get(): number;") != null);
}

test "tsType maps enums to string union" {
    const E = enum { ok, not_found, internal_error };
    const ts = comptime tsType(E);
    try testing.expect(std.mem.indexOf(u8, ts, "\"ok\"") != null);
    try testing.expect(std.mem.indexOf(u8, ts, "\"notFound\"") != null);
    try testing.expect(std.mem.indexOf(u8, ts, "\"internalError\"") != null);
}
