// comptime .d.ts generator. walks `Module` the same way `module.zig`
// does and emits one declaration per js-visible export.

const std = @import("std");
const util = @import("util.zig");
const val_mod = @import("val.zig");
const env_mod = @import("env.zig");
const class_mod = @import("class.zig");
const module = @import("module.zig");

const Val = val_mod.Val;
const Env = env_mod.Env;

/// emit a complete .d.ts string for `Module` at comptime.
pub fn generate(comptime Module: type) []const u8 {
    return "// auto-generated by napi-zig. do not edit.\n\n" ++ comptime emitNamespace(Module, 0, .top);
}

const Where = enum { top, nested };

fn emitNamespace(comptime T: type, comptime indent: usize, comptime where: Where) []const u8 {
    comptime {
        var out: []const u8 = "";
        const pad = spaces(indent);

        for (@typeInfo(T).@"struct".decls) |decl| {
            if (decl.name[0] == '_') continue;
            const js_name = util.snakeToCamel(decl.name);

            switch (module.classify(T, decl.name)) {
                .skip => {},
                .func => out = out ++ emitFn(js_name, @TypeOf(@field(T, decl.name)), indent, where),
                .constant => {
                    const kw = if (where == .top) "export const " else pad ++ "const ";
                    out = out ++ kw ++ js_name ++ ": " ++ tsType(@TypeOf(@field(T, decl.name))) ++ ";\n";
                },
                .class => out = out ++ emitClass(js_name, @field(T, decl.name), indent, where),
                .namespace => {
                    const kw = if (where == .top) "export namespace " else pad ++ "namespace ";
                    out = out ++ kw ++ js_name ++ " {\n";
                    out = out ++ emitNamespace(@field(T, decl.name), indent + 2, .nested);
                    out = out ++ pad ++ "}\n\n";
                },
            }
        }
        return out;
    }
}

fn emitFn(comptime js_name: []const u8, comptime Fn: type, comptime indent: usize, comptime where: Where) []const u8 {
    comptime {
        const info = @typeInfo(Fn).@"fn";
        const params = info.params;
        const kw = if (where == .top) "export function " else spaces(indent) ++ "function ";

        // raw mode (env, callinfo) has no inferable signature.
        if (params.len >= 2 and
            params[0].type.? == Env and
            params[1].type.? == val_mod.CallInfo)
        {
            return kw ++ js_name ++ "(...args: unknown[]): unknown;\n";
        }

        const start: usize = if (params.len > 0 and params[0].type.? == Env) 1 else 0;
        return kw ++ js_name ++ "(" ++ paramList(params, start) ++ "): " ++ returnTs(info) ++ ";\n";
    }
}

fn emitClass(comptime js_name: []const u8, comptime Wrapper: type, comptime indent: usize, comptime where: Where) []const u8 {
    comptime {
        const T = Wrapper.__napi_class_inner;
        const pad = spaces(indent);
        const inner = spaces(indent + 2);
        const prefix = if (where == .top) "export class " else pad ++ "class ";

        const init_info = @typeInfo(@TypeOf(@field(T, "init"))).@"fn";
        const init_skip: usize = if (init_info.params.len > 0 and init_info.params[0].type.? == Env) 1 else 0;

        var out: []const u8 = prefix ++ js_name ++ " {\n";
        out = out ++ inner ++ "constructor(" ++ paramList(init_info.params, init_skip) ++ ");\n";

        for (class_mod.collectMethods(T)) |m| {
            const m_info = @typeInfo(@TypeOf(@field(T, m))).@"fn";
            const m_skip: usize = if (m_info.params.len > 1 and m_info.params[1].type.? == Env) 2 else 1;
            out = out ++ inner ++ util.snakeToCamel(m) ++ "(" ++
                paramList(m_info.params, m_skip) ++ "): " ++ returnTs(m_info) ++ ";\n";
        }

        return out ++ pad ++ "}\n\n";
    }
}

fn paramList(comptime params: []const std.builtin.Type.Fn.Param, comptime start: usize) []const u8 {
    comptime {
        var out: []const u8 = "";
        for (start..params.len) |i| {
            const T = params[i].type.?;
            if (i > start) out = out ++ ", ";
            const opt = @typeInfo(T) == .optional or
                (@typeInfo(T) == .@"struct" and isAllDefaults(T));
            out = out ++ std.fmt.comptimePrint("a{d}", .{i - start}) ++ (if (opt) "?: " else ": ") ++ tsType(T);
        }
        return out;
    }
}

fn returnTs(comptime info: std.builtin.Type.Fn) []const u8 {
    comptime {
        const Return = info.return_type orelse void;
        const Payload = switch (@typeInfo(Return)) {
            .error_union => |eu| eu.payload,
            else => Return,
        };
        return if (Payload == Val) "unknown" else tsType(Payload);
    }
}

fn tsType(comptime T: type) []const u8 {
    comptime {
        if (T == Val) return "unknown";
        if (T == val_mod.Callback) return "(...args: unknown[]) => unknown";

        return switch (@typeInfo(T)) {
            .void => "void",
            .bool => "boolean",
            .comptime_int, .comptime_float => "number",
            .float => "number",
            .int => |info| if (info.bits <= 53) "number" else "bigint",
            .optional => |opt| tsType(opt.child) ++ " | null",
            .@"enum" => |info| blk: {
                var s: []const u8 = "";
                for (info.fields, 0..) |f, i| {
                    if (i > 0) s = s ++ " | ";
                    s = s ++ "\"" ++ util.snakeToCamel(f.name) ++ "\"";
                }
                break :blk s;
            },
            .pointer => |info| {
                if (info.size == .slice and info.child == u8) return "string";
                if (info.size == .slice) return tsType(info.child) ++ "[]";
                if (info.size == .one) {
                    const child = @typeInfo(info.child);
                    if (child == .array and child.array.child == u8) return "string";
                }
                return "unknown";
            },
            .array => |info| if (info.child == u8) "string" else tsType(info.child) ++ "[]",
            .@"struct" => |info| blk: {
                if (@hasDecl(T, "_dts")) break :blk T._dts;
                if (info.is_tuple) {
                    var s: []const u8 = "[";
                    for (info.fields, 0..) |f, i| {
                        if (i > 0) s = s ++ ", ";
                        s = s ++ tsType(f.type);
                    }
                    break :blk s ++ "]";
                }
                var s: []const u8 = "{ ";
                for (info.fields, 0..) |f, i| {
                    if (i > 0) s = s ++ "; ";
                    const opt = if (f.default_value_ptr != null or @typeInfo(f.type) == .optional) "?" else "";
                    s = s ++ util.snakeToCamel(f.name) ++ opt ++ ": " ++ tsType(f.type);
                }
                break :blk s ++ " }";
            },
            else => "unknown",
        };
    }
}

fn isAllDefaults(comptime T: type) bool {
    inline for (@typeInfo(T).@"struct".fields) |f| {
        if (f.default_value_ptr == null) return false;
    }
    return true;
}

fn spaces(comptime n: usize) []const u8 {
    comptime {
        var s: []const u8 = "";
        for (0..n) |_| s = s ++ " ";
        return s;
    }
}

const testing = std.testing;

test "generate emits export function for plain fn" {
    const M = struct {
        pub fn add(_: i32, _: i32) i32 {
            return 0;
        }
    };
    const dts = comptime generate(M);
    try testing.expect(std.mem.indexOf(u8, dts, "export function add(a0: number, a1: number): number;") != null);
}

test "generate camelCases snake_case names" {
    const M = struct {
        pub fn read_file(_: []const u8) []const u8 {
            return "";
        }
    };
    const dts = comptime generate(M);
    try testing.expect(std.mem.indexOf(u8, dts, "readFile(") != null);
}

test "generate emits namespace for nested struct" {
    const M = struct {
        pub const crypto = struct {
            pub fn hash(_: []const u8) [32]u8 {
                return undefined;
            }
        };
    };
    const dts = comptime generate(M);
    try testing.expect(std.mem.indexOf(u8, dts, "export namespace crypto") != null);
    try testing.expect(std.mem.indexOf(u8, dts, "function hash(") != null);
}

test "generate emits exports for constants" {
    const M = struct {
        pub const version: []const u8 = "1.0.0";
        pub const max_buf: u32 = 4096;
    };
    const dts = comptime generate(M);
    try testing.expect(std.mem.indexOf(u8, dts, "export const version: string;") != null);
    try testing.expect(std.mem.indexOf(u8, dts, "export const maxBuf: number;") != null);
}

test "generate emits export class for napi.class wrapper" {
    const M = struct {
        pub const Counter = class_mod.class("Counter", struct {
            value: i32,
            pub fn init(start: i32) @This() {
                return .{ .value = start };
            }
            pub fn increment(self: *@This()) i32 {
                self.value += 1;
                return self.value;
            }
            pub fn get(self: *const @This()) i32 {
                return self.value;
            }
        });
    };
    const dts = comptime generate(M);
    try testing.expect(std.mem.indexOf(u8, dts, "export class Counter {") != null);
    try testing.expect(std.mem.indexOf(u8, dts, "constructor(a0: number);") != null);
    try testing.expect(std.mem.indexOf(u8, dts, "increment(): number;") != null);
    try testing.expect(std.mem.indexOf(u8, dts, "get(): number;") != null);
}

test "tsType maps enums to string union" {
    const E = enum { ok, not_found, internal_error };
    const ts = comptime tsType(E);
    try testing.expect(std.mem.indexOf(u8, ts, "\"ok\"") != null);
    try testing.expect(std.mem.indexOf(u8, ts, "\"notFound\"") != null);
    try testing.expect(std.mem.indexOf(u8, ts, "\"internalError\"") != null);
}
