import {
  existsSync,
  readdirSync,
  statSync,
  mkdirSync,
  copyFileSync,
  writeFileSync,
  readFileSync,
  rmSync,
} from "node:fs";
import { join, relative } from "node:path";
import ora from "ora";
import { run } from "./utils";

export interface BuildDevOptions {
  // Suppress the per-file `info` lines about created/copied loader and .d.ts
  // files. Used by `napi new` for a quiet scaffold flow.
  quiet?: boolean;
}

export async function buildDev(
  optimize: string | undefined,
  options?: BuildDevOptions,
): Promise<void> {
  const optFlag = optimize ? ` --release=${optimize}` : "";
  const quiet = options?.quiet ?? false;

  const spinner = ora("Building for current platform...").start();
  try {
    await run(`zig build${optFlag}`);
  } catch (e) {
    spinner.fail("Build failed");
    const stderr = String((e as { stderr?: string }).stderr ?? "");
    if (stderr) console.error(stderr.trim());
    throw e;
  }
  spinner.succeed("Build complete");

  const libDir = join(process.cwd(), "zig-out", "lib");
  if (!existsSync(libDir)) return;

  for (const file of readdirSync(libDir)) {
    if (!file.endsWith(".node")) continue;

    const name = file.replace(".node", "");
    const loaderPath = join(process.cwd(), `${name}.js`);

    if (!existsSync(loaderPath)) {
      writeFileSync(loaderPath, `module.exports = require('./zig-out/lib/${file}');\n`);
      if (!quiet) ora().info(`Created ${name}.js`);
    }

    const dtsSource = join(libDir, `${name}.d.ts`);
    if (existsSync(dtsSource)) {
      copyFileSync(dtsSource, join(process.cwd(), `${name}.d.ts`));
      if (!quiet) ora().info(`Copied ${name}.d.ts`);
    }
  }
}

export async function buildRelease(optimize: string): Promise<void> {
  const optFlag = ` --release=${optimize}`;

  // zig's WriteFiles step adds without removing, so a renamed scope leaves
  // stale dirs in zig-out/npm that the reconciler would otherwise copy back.
  const srcBase = join(process.cwd(), "zig-out", "npm");
  if (existsSync(srcBase)) rmSync(srcBase, { recursive: true, force: true });

  const spinner = ora("Cross-compiling for all platforms...").start();
  try {
    await run(`zig build -Dnpm=true${optFlag}`);
  } catch (e) {
    spinner.fail("Cross-compilation failed");
    const stderr = String((e as { stderr?: string }).stderr ?? "");
    if (stderr) console.error(stderr.trim());
    throw e;
  }
  spinner.succeed("Cross-compilation complete");

  const destBase = join(process.cwd(), "npm");

  if (!existsSync(srcBase)) {
    ora().fail(
      "No npm output found in zig-out/npm/. Make sure your build.zig uses addLib with .npm config.",
    );
    process.exit(1);
  }

  const syncSpinner = ora("Syncing npm packages...").start();

  const generatedPkgs = readdirSync(srcBase).filter((n) =>
    statSync(join(srcBase, n)).isDirectory(),
  );

  const notes: string[] = [];

  for (const pkgName of generatedPkgs) {
    const srcPkg = join(srcBase, pkgName);
    const destPkg = join(destBase, pkgName);

    const fresh = !existsSync(destPkg);
    mkdirSync(destPkg, { recursive: true });
    const result = reconcilePackage(srcPkg, destPkg);
    syncSpinner.text = fresh ? `Created npm/${pkgName}/` : `Reconciled npm/${pkgName}/`;
    notes.push(...result.notes);
  }

  syncSpinner.succeed("npm packages synced");

  for (const note of notes) ora().info(note);

  if (existsSync(destBase)) {
    const generated = new Set(generatedPkgs);
    const orphans = readdirSync(destBase)
      .filter((n) => statSync(join(destBase, n)).isDirectory())
      .filter((n) => !generated.has(n));

    if (orphans.length > 0) {
      console.log();
      ora().warn(
        `Orphan director${orphans.length > 1 ? "ies" : "y"} in npm/: ${orphans
          .map((n) => `npm/${n}/`)
          .join(", ")}`,
      );
      console.log(`  These do not match any package generated by build.zig. If you renamed`);
      console.log(`  the addon's .name, copy any user fields from the old main package.json`);
      console.log(`  into the new one and delete the orphan folder(s).`);
    }
  }
}

interface ReconcileResult {
  notes: string[];
}

function reconcilePackage(src: string, dest: string): ReconcileResult {
  const notes: string[] = [];

  const existingMain = readJson(join(dest, "package.json")) ?? {};
  const generatedMain = readJson(join(src, "package.json")) ?? {};
  const version = (existingMain.version as string | undefined) ?? "0.0.0";

  const oldScopes = scopesFromOptionalDeps(existingMain.optionalDependencies);
  const newScopes = scopesFromOptionalDeps(generatedMain.optionalDependencies);
  if (oldScopes.size > 0 && !setsEqual(oldScopes, newScopes)) {
    notes.push(
      `Scope changed: ${formatScopes(oldScopes)} → ${formatScopes(newScopes)}. Migrating bindings.`,
    );
  }

  const merged = mergeMainPackageJson(existingMain, generatedMain, version);
  writeJson(join(dest, "package.json"), merged);

  for (const f of ["binding.js", "index.d.ts"]) {
    const srcF = join(src, f);
    if (existsSync(srcF)) copyFileSync(srcF, join(dest, f));
  }

  // index.js is the user's seam: seed once, then leave it alone.
  const srcIndex = join(src, "index.js");
  const destIndex = join(dest, "index.js");
  if (!existsSync(destIndex) && existsSync(srcIndex)) {
    copyFileSync(srcIndex, destIndex);
  }

  const newBindings = listBindingDirs(src);
  const newBindingSet = new Set(newBindings);

  for (const rel of newBindings) {
    const srcBind = join(src, rel);
    const destBind = join(dest, rel);
    mkdirSync(destBind, { recursive: true });

    for (const f of readdirSync(srcBind)) {
      if (f.endsWith(".node")) {
        copyFileSync(join(srcBind, f), join(destBind, f));
      }
    }

    const generated = readJson(join(srcBind, "package.json")) ?? {};
    const existing = readJson(join(destBind, "package.json")) ?? undefined;
    const mergedBind = mergeBindingPackageJson(existing, generated, version);
    writeJson(join(destBind, "package.json"), mergedBind);
  }

  for (const rel of listBindingDirs(dest)) {
    if (!newBindingSet.has(rel)) {
      rmSync(join(dest, rel), { recursive: true, force: true });
    }
  }

  // an entire scope renamed will leave the old scope dir empty after the loop above.
  for (const entry of readdirSync(dest)) {
    if (!entry.startsWith("@")) continue;
    const scopeDir = join(dest, entry);
    if (!statSync(scopeDir).isDirectory()) continue;
    if (readdirSync(scopeDir).length === 0) rmSync(scopeDir, { recursive: true });
  }

  return { notes };
}

const MAIN_POLICY_FIELDS = new Set([
  "name",
  "type",
  "main",
  "types",
  "files",
  "optionalDependencies",
  "version",
]);

const BINDING_POLICY_FIELDS = new Set(["name", "os", "cpu", "libc", "main", "files", "version"]);

// start from generated (canonical field order + policy fields), layer the
// existing file's user fields on top, then force version + lockstep deps.
function mergeMainPackageJson(
  existing: Record<string, unknown>,
  generated: Record<string, unknown>,
  version: string,
): Record<string, unknown> {
  const out: Record<string, unknown> = { ...generated };

  for (const [k, v] of Object.entries(existing)) {
    if (!MAIN_POLICY_FIELDS.has(k)) out[k] = v;
  }

  if (out.optionalDependencies && typeof out.optionalDependencies === "object") {
    const deps: Record<string, string> = {};
    for (const k of Object.keys(out.optionalDependencies as Record<string, unknown>)) {
      deps[k] = version;
    }
    out.optionalDependencies = deps;
  }

  out.version = version;
  return out;
}

function mergeBindingPackageJson(
  existing: Record<string, unknown> | undefined,
  generated: Record<string, unknown>,
  version: string,
): Record<string, unknown> {
  const out: Record<string, unknown> = { ...generated };

  if (existing) {
    for (const [k, v] of Object.entries(existing)) {
      if (!BINDING_POLICY_FIELDS.has(k)) out[k] = v;
    }
  }

  out.version = version;
  return out;
}

function listBindingDirs(root: string): string[] {
  const result: string[] = [];
  for (const scope of readdirSync(root)) {
    if (!scope.startsWith("@")) continue;
    const scopePath = join(root, scope);
    if (!statSync(scopePath).isDirectory()) continue;

    for (const bind of readdirSync(scopePath)) {
      const bindPath = join(scopePath, bind);
      if (!statSync(bindPath).isDirectory()) continue;
      result.push(relative(root, bindPath));
    }
  }
  return result;
}

function scopesFromOptionalDeps(deps: unknown): Set<string> {
  const out = new Set<string>();
  if (!deps || typeof deps !== "object") return out;
  for (const k of Object.keys(deps as Record<string, unknown>)) {
    if (k.startsWith("@")) {
      const scope = k.split("/")[0];
      if (scope) out.add(scope);
    }
  }
  return out;
}

function setsEqual<T>(a: Set<T>, b: Set<T>): boolean {
  if (a.size !== b.size) return false;
  for (const v of a) if (!b.has(v)) return false;
  return true;
}

function formatScopes(s: Set<string>): string {
  if (s.size === 0) return "(none)";
  return [...s].join(", ");
}

function readJson(path: string): Record<string, unknown> | undefined {
  if (!existsSync(path)) return undefined;
  return JSON.parse(readFileSync(path, "utf-8")) as Record<string, unknown>;
}

function writeJson(path: string, value: Record<string, unknown>): void {
  writeFileSync(path, JSON.stringify(value, null, 2) + "\n");
}
